micronaut:
  application:
    name: holidays
mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
  automatic-class-models: false
grpc:
  channels:
    users:
      address: ${USERS_HOST:localhost}:${USERS_PORT:8081}
      plaintext: true
  server:
    port: 8082
